name: Open AI Subsystem CI/CD
on:
    pull_request:
    push:
        branches: [main]

jobs:
  test-open-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env from secrets
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Build and test with Docker Compose
        run: |
          docker compose build
          docker compose up -d
          docker compose exec open-ai pytest
          docker compose down

  deploy:
    needs: test-open-ai
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag open-ai_openai ${{ secrets.DOCKERHUB_USERNAME }}/open-ai:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/open-ai:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
              # Navigate to project directory
              cd /home/swe/5-final-proj5-febv

              # Pull latest code
              git pull origin main

              # Stop and remove existing containers
              docker compose down

              # Build and start new containers
              docker compose up -d --build

              # Clean up unused images
              docker image prune -f
